import type { RecipeEntry } from "./extra-recipes";

type Food={name:string;protein:number;carbs:number;fat:number};
// Approximate generic composition per 100 g. Actual brand/weight changes the estimate.
const foods:Record<string,Food>={};
function food(id:string,name:string,p:number,c:number,f:number){foods[id]={name,protein:p,carbs:c,fat:f}}
const rows:[string,string,number,number,number][]=[
 ["egg","Huevos",12.6,1,10], ["oil","Aceite de oliva",0,0,100], ["potato","Patatas",2,17,0.1], ["rice","Arroz",7,78,1], ["pasta","Pasta",12,72,1.5], ["quinoa","Quinoa",14,64,6], ["couscous","Cuscús",13,72,2],
 ["chicken","Pechuga de pollo",23,0,2], ["turkey","Pechuga de pavo",24,0,2], ["beef","Ternera",21,0,6], ["pork","Solomillo de cerdo",22,0,4], ["salmon","Salmón",20,0,13], ["hake","Merluza",18,0,2], ["cod","Bacalao desalado",18,0,1], ["prawn","Gambas peladas",20,0,1], ["tuna","Atún al natural",24,0,1], ["tofu","Tofu",13,2,7], ["seitan","Seitán",24,5,2],
 ["ham","Jamón ibérico",30,1,20], ["chorizo","Chorizo",24,2,35], ["bacon","Bacon",15,1,40], ["deli","Pavo en lonchas",18,2,3], ["sardine","Sardinas en conserva",24,0,12], ["chickpea","Garbanzos cocidos",7,20,3], ["lentil","Lentejas cocidas",8,18,1], ["whitebean","Alubias blancas cocidas",7,17,1], ["redbean","Alubias rojas cocidas",8,18,1],
 ["spinach","Espinacas",3,2,0.4], ["mushroom","Champiñones",3,1,0.3], ["asparagus","Espárragos verdes",2,2,0.2], ["zucchini","Calabacín",1,3,0.2], ["pepper","Pimiento rojo",1,5,0.2], ["onion","Cebolla",1,8,0.1], ["tomato","Tomate",1,4,0.2], ["cherry","Tomate cherry",1,4,0.2], ["broccoli","Brócoli",3,4,0.4], ["carrot","Zanahoria",1,7,0.2], ["peas","Guisantes",5,10,0.5], ["pumpkin","Calabaza",1,6,0.1], ["leek","Puerro",1,5,0.2], ["cauliflower","Coliflor",2,3,0.3], ["aubergine","Berenjena",1,4,0.2], ["lettuce","Lechuga",1,2,0.2], ["rocket","Rúcula",2,2,0.4], ["cucumber","Pepino",1,2,0.1], ["beet","Remolacha cocida",1,8,0.2], ["avocado","Aguacate",2,2,15], ["corn","Maíz dulce",3,15,1],
 ["cheese","Queso semicurado",25,1,28], ["feta","Queso feta",14,2,21], ["mozzarella","Mozzarella",18,2,17], ["goat","Queso de cabra",20,2,24], ["fresh","Queso fresco",12,3,8], ["creamcheese","Queso crema",6,4,22], ["yogurt","Yogur natural",4,5,3], ["skyr","Skyr natural",10,4,0.3], ["milk","Leche",3.3,5,1.6], ["oatmilk","Bebida de avena",1,7,1.5],
 ["bread","Pan integral",10,42,3], ["wrap","Tortillas de trigo",8,50,7], ["dough","Masa de pizza",8,45,5], ["sauce","Tomate triturado",1,4,0.2], ["oregano","Orégano",9,26,4], ["paprika","Pimentón dulce",14,35,13], ["curry","Curry",14,35,14], ["garlic","Ajo",6,28,0.5], ["lemon","Limón",1,3,0.3], ["vinegar","Vinagre de vino",0,0.5,0], ["oats","Avena",13,60,7], ["flour","Harina de trigo",10,73,1], ["baking","Levadura química",0,28,0], ["banana","Plátano",1,21,0.3], ["apple","Manzana",0.3,12,0.2], ["pear","Pera",0.4,12,0.2], ["strawberry","Fresas",0.7,6,0.3], ["blueberry","Arándanos",0.7,12,0.3], ["mango","Mango",0.6,14,0.3], ["kiwi","Kiwi",1,10,0.5], ["peach","Melocotón",0.8,8,0.2], ["pineapple","Piña",0.5,12,0.1], ["orange","Naranja",1,9,0.2], ["cocoa","Cacao puro en polvo",20,12,21], ["walnut","Nueces",15,7,65], ["almond","Almendras",21,6,54], ["peanut","Crema de cacahuete",25,14,50], ["cinnamon","Canela",4,28,1], ["hummus","Hummus",6,14,12]
];
rows.forEach(r=>food(...r));
type Part=[string,number];
const made:RecipeEntry[]=[];
const hob=["Placa / inducción","Gas"];
const veg=["spinach","mushroom","asparagus","zucchini","pepper","broccoli","carrot","peas"];
const proteins=["chicken","turkey","beef","pork","salmon","hake","prawn","tofu","seitan","tuna","chickpea","lentil"];
const fruits=["banana","apple","pear","strawberry","blueberry","mango","kiwi","peach","pineapple","orange"];
const name=(id:string)=>foods[id].name.toLocaleLowerCase("es");
const freshProtein=new Set(["chicken","turkey","beef","pork","salmon","hake","cod","prawn"]);
function cook(id:string){return freshProtein.has(id)?`Cocina ${name(id)} por completo en una sartén; corta las aves en dados pequeños y comprueba el centro antes de servir.`:/chickpea|lentil|bean/.test(id)?`Escurre y enjuaga ${name(id)}; ya están cocidos, solo hay que calentarlos.`:id==="tuna"||id==="sardine"?`Escurre ${name(id)}; añade al final, ya está cocinado.`:`Dora ${name(id)} en una sartén antiadherente.`}
function add(title:string,family:string,parts:Part[],steps:string[],image:string,time:number,mealTypes:RecipeEntry["mealTypes"],tools:string[]=hob){
 if(made.some(r=>r.title===title))return;
 const servings=2,totals={protein:0,carbs:0,fat:0};
 const combined=new Map<string,number>();for(const [id,g] of parts)combined.set(id,(combined.get(id)||0)+g);
 const ingredients=[...combined].map(([id,g])=>{
  const f=foods[id];if(!f)throw new Error(id);
  totals.protein+=f.protein*g/100/servings;totals.carbs+=f.carbs*g/100/servings;totals.fat+=f.fat*g/100/servings;
  const unit=id==="egg"?"uds":id==="milk"||id==="oatmilk"||id==="oil"?"ml":"g";
  const amount=id==="egg"?g/50:g;
  return {name:f.name,qty:amount+" "+unit,key:f.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")};
 });
 const calories=Math.round(totals.protein*4+totals.carbs*4+totals.fat*9);
 made.push({id:"v-"+title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/-$/,""),title,family,mealTypes,image,photoCaption:"Foto orientativa de esta familia de recetas",time,difficulty:"Fácil",servings,calories,protein:Math.round(totals.protein),carbs:Math.round(totals.carbs),fat:Math.round(totals.fat),ingredients,steps,tools,mode:time<=25?["rapido","normal","mealprep"]:["normal","cocinar","mealprep"],description:`${title}. Cantidades para dos personas; pesos de arroz y pasta en seco y de legumbres cocidas escurridas. Valores nutricionales aproximados.`});
}
// Each combination below is culinary: preparation, ingredient quantities and names change together.
const scrambleFillings=["ham","chorizo","bacon","deli","tuna","prawn","spinach","mushroom","asparagus","zucchini","pepper","onion","tomato","peas","fresh","goat"];
for(const filling of scrambleFillings)for(const base of ["none","potato","bread"]){
 const parts:Part[]=[["egg",200],[filling,fillingsAmount(filling)],["oil",10]];
 if(base!=="none")parts.push([base,base==="potato"?300:120]);
 const title=`Revuelto de ${name(filling)}${base==="potato"?" con patatas":base==="bread"?" sobre pan integral":" sin patatas"}`;
 add(title,"Revuelto",parts,[...(base==="potato"?["Pela las patatas, córtalas en dados pequeños y cuécelas 10–12 minutos hasta que estén tiernas; escurre."]:[]),`Trocea ${name(filling)}. Calienta el aceite y ${freshProtein.has(filling)?"cocínalo completamente":filling==="tuna"?"incorpora el atún escurrido al final":"saltea el relleno hasta que esté tierno"}.`,"Bate los huevos e incorpóralos a fuego suave. Remueve hasta que queden cuajados.",base==="bread"?"Sirve el revuelto sobre las tostadas de pan integral.":"Sirve al momento."],"/recipe-images/x08.webp",base==="potato"?25:12,["Desayuno","Cena"]);
}
function fillingsAmount(id:string){return ["ham","chorizo","bacon","deli"].includes(id)?70:["fresh","goat"].includes(id)?100:180}
for(const filling of scrambleFillings)for(const potato of [false,true])add(`Tortilla de ${name(filling)}${potato?" y patata":""}`,"Tortilla",[["egg",200],[filling,fillingsAmount(filling)],["oil",12],...(potato?[["potato",300] as Part]:[])],[...(potato?["Cuece las patatas en dados pequeños hasta que estén tiernas y escurre."]:[]),`Trocea y saltea ${name(filling)}; si usas gambas, cocínalas completamente. Escurre el atún si corresponde.`,"Bate los huevos y mezcla con el relleno.","Cuaja en sartén antiadherente a fuego medio-bajo por los dos lados, hasta que el centro esté cocinado."],"/recipe-images/x07.webp",potato?30:15,["Desayuno","Comida","Cena"]);
for(const protein of proteins)for(const vegetable of veg.slice(0,5))add(`Arroz con ${name(protein)} y ${name(vegetable)}`,"Arroz",[["rice",160],[protein,protein==="chickpea"||protein==="lentil"?300:300],[vegetable,250],["oil",15]],["Cuece el arroz según el envase y escurre si hace falta.",cook(protein),`Trocea y saltea ${name(vegetable)} con el aceite hasta que esté tierno.`,"Mezcla el arroz y el resto de ingredientes y calienta el conjunto. Sirve o reparte en recipientes pequeños y refrigera antes de que transcurran dos horas."],"/recipe-images/x21.webp",30,["Comida","Cena"]);
const pastaFillings=["chicken","turkey","tuna","tofu","mushroom","spinach","prawn","chickpea"];
for(const protein of pastaFillings)for(const sauce of ["tomato","mozzarella","yogurt","creamcheese","pumpkin"]){
 const extra:Part[]=sauce==="tomato"?[["sauce",300]]:sauce==="pumpkin"?[["pumpkin",250],["milk",100]]:sauce==="yogurt"?[["yogurt",180]]:[[sauce,100],["milk",100]];
 add(`Pasta con ${name(protein)} y salsa de ${name(sauce)}`,"Pasta",[["pasta",160],[protein,220],["oil",10],...extra],["Cuece la pasta al dente y reserva medio vaso del agua de cocción.",cook(protein),sauce==="pumpkin"?"Cuece la calabaza 12–15 minutos y tritúrala con la leche.":sauce==="tomato"?"Cocina el tomate triturado 8–10 minutos con el aceite.":sauce==="yogurt"?"Baja el fuego y añade el yogur al final, sin hervir.":`Funde ${name(sauce)} con la leche a fuego suave.`,"Mezcla la pasta con el relleno y la salsa. Aligera con el agua reservada si hace falta."],sauce==="tomato"?"/recipe-images/x02.webp":"/recipe-images/r2.webp",25,["Comida","Cena"]);
}
const saladProteins=["chicken","turkey","tuna","sardine","chickpea","lentil","whitebean","tofu","feta","fresh"];
for(const protein of saladProteins)for(const base of ["lettuce","rocket","rice","quinoa","couscous","potato"]){
 const grain=["rice","quinoa","couscous"].includes(base),amount=grain?140:base==="potato"?350:150;
 add(`Ensalada de ${name(base)} con ${name(protein)}`,"Ensalada",[[base,amount],[protein,protein==="feta"||protein==="fresh"?140:260],["tomato",220],["cucumber",150],["oil",15],["vinegar",10]],[grain?`Cuece ${name(base)} siguiendo el envase y enfría rápidamente antes de mezclar.`:base==="potato"?"Cuece las patatas 15–20 minutos, deja templar y corta.":"Lava y escurre las hojas.",freshProtein.has(protein)||protein==="tofu"?cook(protein):`Escurre o corta ${name(protein)}.`,"Lava y corta el tomate y el pepino.","Monta la ensalada y aliña con aceite y vinagre justo antes de servir."],"/recipe-images/x28.webp",grain||base==="potato"?25:15,["Comida","Cena"]);
}
for(const legume of ["lentil","chickpea","whitebean","redbean"])for(const vegetable of veg)add(`Guiso rápido de ${name(legume)} con ${name(vegetable)}`,"Legumbres",[[legume,500],[vegetable,250],["onion",100],["sauce",150],["oil",15],["paprika",2]],["Pica la cebolla y rehógala con el aceite.",`Añade ${name(vegetable)} y cocina hasta que se ablande.`,"Incorpora el pimentón y el tomate, remueve y añade las legumbres cocidas escurridas.","Cubre con agua a la textura deseada y cocina a fuego suave 10 minutos."],legume==="lentil"?"/recipe-images/x12.webp":"/recipe-images/x13.webp",25,["Comida","Cena"]);
const pizzaToppings=["ham","chorizo","bacon","tuna","chicken","turkey","mushroom","spinach","pepper","aubergine","goat","prawn"];
for(const topping of pizzaToppings)for(const second of ["none","onion","cherry","zucchini"]){
 add(`Pizza de ${name(topping)}${second==="none"?"":" y "+name(second)}`,"Pizza",[["dough",300],["sauce",160],["mozzarella",140],[topping,fillingsAmount(topping)],...(second!=="none"?[[second,120] as Part]:[]),["oregano",1]],["Precalienta el horno a 220 °C y extiende la masa sobre papel de horno.",freshProtein.has(topping)?cook(topping):`Trocea ${name(topping)}; escurre el atún o saltea las verduras unos minutos.`,"Reparte tomate, mozzarella y los ingredientes sobre la masa; añade orégano.","Hornea 12–18 minutos, siguiendo también el tiempo indicado por la masa, hasta que la base esté cocida y el queso fundido."],"/recipe-images/x20.webp",30,["Comida","Cena"],["Horno"]);
}
for(const protein of ["chicken","turkey","tuna","deli","ham","tofu","hummus","fresh","feta","sardine"])for(const format of ["wrap","sandwich","toast"]){
 add(`${format==="wrap"?"Wrap":format==="sandwich"?"Sándwich":"Tostadas"} de ${name(protein)} y tomate`,format==="wrap"?"Wrap":"Tostada",[[format==="wrap"?"wrap":"bread",140],[protein,180],["tomato",160],["lettuce",60]],[freshProtein.has(protein)||protein==="tofu"?cook(protein):`Prepara ${name(protein)}; escurre si es una conserva.`,"Lava y corta el tomate y la lechuga.",format==="wrap"?"Calienta las tortillas unos segundos y rellena; enrolla doblando los extremos.":"Tuesta el pan si quieres y coloca el relleno y las verduras.","Sirve recién montado."],format==="wrap"?"/recipe-images/x05.webp":"/recipe-images/x29.webp",freshProtein.has(protein)?20:8,["Desayuno","Comida","Cena"],freshProtein.has(protein)||protein==="tofu"?hob:[]);
}
for(const protein of ["chicken","turkey","pork","salmon","hake","cod","tofu","seitan"])for(const side of ["potato","pumpkin","broccoli","zucchini","carrot"]){
 add(`${foods[protein].name} al horno con ${name(side)}`,"Horno",[[protein,320],[side,400],["oil",20],["lemon",40],["garlic",5]],["Precalienta el horno a 200 °C.",`Trocea ${name(side)}; corta fino la patata, zanahoria o calabaza. Mezcla con aceite y ajo.`,"Hornea la guarnición 15–20 minutos si es una hortaliza dura; 5–10 si es brócoli o calabacín.",`Añade ${name(protein)} y cocina otros 12–20 minutos según grosor, hasta que esté totalmente hecho. Para aves, comprueba el centro de la pieza.`,"Termina con el limón y sirve."],protein==="salmon"?"/recipe-images/x09.webp":"/recipe-images/x23.webp",40,["Comida","Cena"],["Horno"]);
}
for(const vegetable of ["pumpkin","zucchini","carrot","broccoli","cauliflower","leek","spinach","peas","asparagus","mushroom","tomato","aubergine"])for(const enriched of [false,true])add(`Crema de ${name(vegetable)}${enriched?" con garbanzos":" y patata"}`,"Crema",[[vegetable,400],[enriched?"chickpea":"potato",enriched?300:200],["onion",80],["oil",15],["bread",100]],["Lava y trocea las hortalizas.","Rehoga la cebolla con aceite y añade la verdura.",enriched?"Añade agua hasta cubrir y cuece 15–20 minutos; incorpora los garbanzos cocidos escurridos los últimos 5 minutos.":"Añade la patata en dados, cubre con agua y cuece 20 minutos hasta que esté tierna.","Tritura y ajusta el espesor con agua. Sirve con el pan integral."],"/recipe-images/x27.webp",30,["Comida","Cena"]);
for(const fruit of fruits.slice(0,8))for(const topping of ["walnut","almond","peanut"]){
 add(`Avena con ${name(fruit)} y ${name(topping)}`,"Avena",[["oats",110],["milk",350],[fruit,200],[topping,25]],["Calienta la leche y añade la avena.","Cuece 4–5 minutos a fuego suave, removiendo.",`Lava, pela si hace falta y corta ${name(fruit)}.`,`Reparte la avena en dos cuencos y añade la fruta y ${name(topping)}.`],"/recipe-images/x17.webp",10,["Desayuno","Merienda"]);
}
for(const fruit of fruits)for(const dairy of ["yogurt","skyr","fresh"])add(`Bol de ${name(dairy)} con ${name(fruit)} y avena`,"Bol de yogur",[[dairy,300],[fruit,240],["oats",90],["walnut",20]],[`Reparte ${name(dairy)} en dos cuencos.`,`Lava, pela si procede y corta ${name(fruit)}.`,"Añade la fruta, los copos de avena y las nueces troceadas.","Sirve al momento; si lo preparas antes, mantenlo refrigerado."],"/recipe-images/yogur-fruta-avena.webp",5,["Desayuno","Merienda"],[]);
for(const fruit of fruits)for(const dairy of ["milk","oatmilk"])add(`Batido de ${name(fruit)} con ${name(dairy)} y avena`,"Batido",[[fruit,260],[dairy,400],["oats",70],["almond",20]],[`Prepara ${name(fruit)} y retira semillas o hueso cuando corresponda.`,"Añade a la batidora con el líquido, la avena y las almendras.","Tritura hasta que quede homogéneo; añade agua si quieres aligerarlo.","Sirve al momento o conserva en frío."],"/recipe-images/x16.webp",5,["Desayuno","Merienda"],["Batidora","Thermomix / robot"]);
for(const fruit of fruits.slice(0,8))for(const chocolate of [false,true])add(`Tortitas de avena con ${name(fruit)}${chocolate?" y cacao":""}`,"Tortitas",[["oats",120],["egg",100],["milk",180],[fruit,200],["oil",8],["baking",4],...(chocolate?[["cocoa",12] as Part]:[])],["Usa copos de avena finos para que la mezcla quede homogénea.","Mezcla la avena con los huevos, la leche y la levadura química; añade el cacao si corresponde y deja reposar 5 minutos.","Calienta la sartén con una película de aceite y cocina pequeñas tortitas 2–3 minutos por cada lado.",`Sirve con ${name(fruit)} cortado.`],chocolate?"/recipe-images/x32.webp":"/recipe-images/r5.webp",20,["Desayuno","Merienda"],hob);
export const EXPANDED_RECIPES=made;
