export type RecipeEntry={
 id:string; title:string; image:string; time:number; difficulty:"Fácil"|"Media";
 mode:("rapido"|"normal"|"cocinar"|"mealprep")[]; servings:number; calories:number; protein:number; carbs:number; fat:number;
 ingredients:{name:string;qty:string;key:string}[]; steps:string[]; description:string; tools?:string[];
 country?:string; nutritionUnavailable?:boolean; toolGroups?:string[][]; family?:string; mealTypes?:("Desayuno"|"Comida"|"Cena"|"Merienda")[]; photoCaption?:string;
};

export const EXTRA_RECIPES:RecipeEntry[]=[
 {id:"x01",title:"Carbonara sencilla",image:"/recipe-images/x01.webp",time:25,difficulty:"Fácil",mode:["normal","cocinar"],servings:4,calories:610,protein:29,carbs:72,fat:23,description:"Pasta cremosa con huevo, queso y bacon.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Pasta",qty:"320 g",key:"pasta"},{name:"Huevos",qty:"3 uds",key:"huevo"},{name:"Bacon",qty:"120 g",key:"bacon"},{name:"Queso",qty:"100 g",key:"queso"}],steps:["Cuece la pasta.","Dora el bacon.","Mezcla huevo y queso fuera del fuego.","Integra con la pasta caliente sin dejar que el huevo se convierta en revuelto."]},
 {id:"x02",title:"Pasta con tomate y mozzarella",image:"/recipe-images/x02.webp",time:20,difficulty:"Fácil",mode:["rapido","normal"],servings:4,calories:520,protein:22,carbs:75,fat:14,description:"Para gastar tomate y mozzarella en una comida rápida.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Pasta",qty:"320 g",key:"pasta"},{name:"Tomate",qty:"4 uds",key:"tomate"},{name:"Mozzarella",qty:"200 g",key:"mozzarella"}],steps:["Cuece la pasta.","Cocina el tomate troceado con aceite.","Mezcla pasta y tomate.","Añade mozzarella al final."]},
 {id:"x03",title:"Pollo al curry con yogur",image:"/recipe-images/x03.webp",time:30,difficulty:"Fácil",mode:["normal","mealprep"],servings:4,calories:540,protein:45,carbs:55,fat:15,description:"Usa yogur para una salsa cremosa sin complicarte.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Pechuga de pollo",qty:"700 g",key:"pollo"},{name:"Yogur natural",qty:"2 uds",key:"yogur"},{name:"Arroz",qty:"280 g",key:"arroz"},{name:"Curry",qty:"10 g",key:"curry"}],steps:["Cuece el arroz.","Dora el pollo hasta que esté completamente cocinado.","Baja el fuego, añade curry y yogur.","Mezcla suavemente y sirve con arroz."]},
 {id:"x04",title:"Ensalada de pollo con salsa de yogur",image:"/recipe-images/x04.webp",time:20,difficulty:"Fácil",mode:["rapido","normal"],servings:4,calories:390,protein:38,carbs:22,fat:16,description:"Ligera y útil para gastar pollo, lechuga y yogur.",tools:["Placa / inducción","Gas","Air fryer"],ingredients:[{name:"Pechuga de pollo",qty:"600 g",key:"pollo"},{name:"Lechuga",qty:"1 ud",key:"lechuga"},{name:"Tomate",qty:"2 uds",key:"tomate"},{name:"Yogur natural",qty:"1 ud",key:"yogur"}],steps:["Cocina completamente el pollo y córtalo.","Lava y corta las verduras.","Mezcla yogur con limón o especias.","Monta la ensalada."]},
 {id:"x05",title:"Wrap de pollo y verduras",image:"/recipe-images/x05.webp",time:20,difficulty:"Fácil",mode:["rapido","mealprep"],servings:4,calories:470,protein:37,carbs:48,fat:15,description:"Fácil de llevar fuera de casa.",tools:["Placa / inducción","Gas","Air fryer"],ingredients:[{name:"Pechuga de pollo",qty:"600 g",key:"pollo"},{name:"Tortillas de trigo",qty:"4 uds",key:"tortilla"},{name:"Lechuga",qty:"1 ud",key:"lechuga"},{name:"Tomate",qty:"2 uds",key:"tomate"}],steps:["Cocina el pollo por completo.","Corta verduras.","Calienta las tortillas.","Rellena y enrolla."]},
 {id:"x06",title:"Arroz con huevo y tomate",image:"/recipe-images/x06.webp",time:20,difficulty:"Fácil",mode:["rapido","normal"],servings:4,calories:480,protein:18,carbs:72,fat:12,description:"Comida de despensa con pocos ingredientes.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Arroz",qty:"300 g",key:"arroz"},{name:"Huevos",qty:"4 uds",key:"huevo"},{name:"Tomate frito",qty:"300 g",key:"tomate"}],steps:["Cuece el arroz.","Calienta el tomate.","Cocina los huevos a tu gusto.","Sirve juntos."]},
 {id:"x07",title:"Tortilla de patata rápida",image:"/recipe-images/x07.webp",time:35,difficulty:"Media",mode:["normal","cocinar"],servings:4,calories:430,protein:18,carbs:40,fat:21,description:"Un clásico con huevos y patata.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Patatas",qty:"600 g",key:"patata"},{name:"Huevos",qty:"6 uds",key:"huevo"},{name:"Cebolla",qty:"1 ud",key:"cebolla"}],steps:["Cocina patata y cebolla hasta que estén tiernas.","Bate los huevos.","Mezcla todo.","Cuaja la tortilla por ambos lados."]},
 {id:"x08",title:"Revuelto de verduras y huevo",image:"/recipe-images/x08.webp",time:15,difficulty:"Fácil",mode:["rapido","normal"],servings:2,calories:310,protein:20,carbs:18,fat:17,description:"Para utilizar pequeñas cantidades de verdura.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Huevos",qty:"4 uds",key:"huevo"},{name:"Verduras variadas",qty:"300 g",key:"verdura"}],steps:["Saltea las verduras.","Añade los huevos batidos.","Remueve hasta que estén cuajados.","Sirve al momento."]},
 {id:"x09",title:"Salmón al horno con patata",image:"/recipe-images/x09.webp",time:35,difficulty:"Fácil",mode:["normal","cocinar"],servings:4,calories:560,protein:39,carbs:42,fat:25,description:"Plato completo con pocos pasos.",tools:["Horno","Air fryer"],ingredients:[{name:"Salmón",qty:"600 g",key:"salmon"},{name:"Patatas",qty:"700 g",key:"patata"},{name:"Limón",qty:"1 ud",key:"limon"}],steps:["Corta las patatas finas y empieza a cocinarlas.","Añade el salmón después.","Cocina hasta que el pescado esté hecho y se separe fácilmente en lascas.","Termina con limón."]},
 {id:"x10",title:"Merluza con verduras",image:"/recipe-images/x10.webp",time:25,difficulty:"Fácil",mode:["rapido","normal"],servings:4,calories:360,protein:37,carbs:25,fat:11,description:"Cena ligera para pescado blanco.",tools:["Horno","Air fryer","Placa / inducción","Gas"],ingredients:[{name:"Merluza",qty:"600 g",key:"merluza"},{name:"Verduras variadas",qty:"500 g",key:"verdura"}],steps:["Prepara las verduras.","Cocínalas hasta que empiecen a estar tiernas.","Añade la merluza.","Termina la cocción hasta que el pescado esté hecho."]},
 {id:"x11",title:"Pollo y patatas en air fryer",image:"/recipe-images/x11.webp",time:30,difficulty:"Fácil",mode:["rapido","normal"],servings:4,calories:520,protein:43,carbs:48,fat:16,description:"Poca preparación y una sola cesta.",tools:["Air fryer"],ingredients:[{name:"Pechuga de pollo",qty:"700 g",key:"pollo"},{name:"Patatas",qty:"700 g",key:"patata"}],steps:["Corta patata y pollo en tamaños regulares.","Condimenta.","Cocina por tandas si hace falta.","Comprueba que el pollo queda completamente cocinado."]},
 {id:"x12",title:"Lentejas rápidas con verduras",image:"/recipe-images/x12.webp",time:30,difficulty:"Fácil",mode:["normal","mealprep"],servings:5,calories:420,protein:22,carbs:65,fat:8,description:"Meal prep barato de despensa.",tools:["Placa / inducción","Gas","Thermomix / robot"],ingredients:[{name:"Lentejas cocidas",qty:"1000 g",key:"lenteja"},{name:"Zanahoria",qty:"2 uds",key:"zanahoria"},{name:"Cebolla",qty:"1 ud",key:"cebolla"},{name:"Tomate",qty:"2 uds",key:"tomate"}],steps:["Sofríe las verduras.","Añade las lentejas cocidas escurridas y agua hasta la textura deseada.","Cocina unos 10 minutos para integrar los sabores.","Divide en raciones."]},
 {id:"x13",title:"Garbanzos con tomate y espinacas",image:"/recipe-images/x13.webp",time:20,difficulty:"Fácil",mode:["rapido","normal","mealprep"],servings:4,calories:390,protein:18,carbs:58,fat:9,description:"Vegetal, rápido y de despensa.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Garbanzos cocidos",qty:"500 g",key:"garbanzo"},{name:"Tomate",qty:"3 uds",key:"tomate"},{name:"Espinacas",qty:"250 g",key:"espinaca"}],steps:["Saltea el tomate.","Añade garbanzos cocidos.","Incorpora espinacas hasta que bajen.","Ajusta especias."]},
 {id:"x14",title:"Bowl de hummus, huevo y verduras",image:"/recipe-images/x14.webp",time:15,difficulty:"Fácil",mode:["rapido","normal"],servings:2,calories:450,protein:20,carbs:38,fat:23,description:"Para montar sin casi cocinar.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Hummus",qty:"200 g",key:"hummus"},{name:"Huevos",qty:"2 uds",key:"huevo"},{name:"Tomate",qty:"2 uds",key:"tomate"},{name:"Pepino",qty:"1 ud",key:"pepino"}],steps:["Cuece o cocina los huevos.","Corta tomate y pepino.","Reparte hummus en dos boles.","Añade el resto encima."]},
 {id:"x15",title:"Yogur con fruta y avena",image:"/recipe-images/yogur-fruta-avena.webp",time:5,difficulty:"Fácil",mode:["rapido"],servings:1,calories:449,protein:16.7,carbs:72.8,fat:12,description:"Desayuno con dos yogures, avena y plátano; las cantidades se pueden adaptar.",ingredients:[{name:"Yogur natural",qty:"2 uds",key:"yogur"},{name:"Plátano",qty:"1 ud",key:"platano"},{name:"Avena",qty:"50 g",key:"avena"}],steps:["Pon el yogur en un bol.","Añade avena.","Corta el plátano.","Sirve."]},
 {id:"x16",title:"Batido de leche, yogur y plátano",image:"/recipe-images/x16.webp",time:5,difficulty:"Fácil",mode:["rapido"],servings:2,calories:280,protein:15,carbs:42,fat:6,description:"Usa leche y yogur juntos cuando quieres aprovechar ambos.",tools:["Batidora","Thermomix / robot"],ingredients:[{name:"Leche",qty:"300 ml",key:"leche"},{name:"Yogur natural",qty:"2 uds",key:"yogur"},{name:"Plátano",qty:"1 ud",key:"platano"}],steps:["Añade todo a la batidora.","Tritura hasta que quede uniforme.","Sirve frío."]},
 {id:"x17",title:"Overnight oats con yogur",image:"/recipe-images/x17.webp",time:5,difficulty:"Fácil",mode:["rapido","mealprep"],servings:2,calories:390,protein:19,carbs:58,fat:9,description:"Se prepara por la noche y deja el desayuno resuelto.",ingredients:[{name:"Avena",qty:"120 g",key:"avena"},{name:"Leche",qty:"250 ml",key:"leche"},{name:"Yogur natural",qty:"2 uds",key:"yogur"}],steps:["Mezcla avena, leche y yogur.","Reparte en recipientes.","Refrigera toda la noche.","Añade fruta al servir si quieres."]},
 {id:"x18",title:"Bizcocho de yogur básico",image:"/recipe-images/x18.webp",time:45,difficulty:"Media",mode:["cocinar"],servings:8,calories:310,protein:7,carbs:45,fat:11,description:"Para gastar yogur en una preparación familiar.",tools:["Horno"],ingredients:[{name:"Yogur natural",qty:"1 ud",key:"yogur"},{name:"Huevos",qty:"3 uds",key:"huevo"},{name:"Harina",qty:"250 g",key:"harina"},{name:"Azúcar",qty:"150 g",key:"azucar"},{name:"Aceite de girasol",qty:"80 ml",key:"aceite de girasol"},{name:"Levadura química",qty:"16 g",key:"levadura"}],steps:["Precalienta el horno a 180 °C. Bate los huevos con el azúcar y añade el yogur y el aceite.","Incorpora la harina y la levadura química sin batir en exceso.","Vierte en molde.","Hornea unos 30–35 minutos; comprueba que al pinchar el centro salga limpio."]},
 {id:"x19",title:"Quesadilla de pollo y queso",image:"/recipe-images/x19.webp",time:15,difficulty:"Fácil",mode:["rapido","normal"],servings:2,calories:520,protein:35,carbs:44,fat:22,description:"Aprovecha pollo cocinado o fresco y queso.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Pollo",qty:"250 g",key:"pollo"},{name:"Queso",qty:"100 g",key:"queso"},{name:"Tortillas de trigo",qty:"4 uds",key:"tortilla"}],steps:["Cocina completamente el pollo si está crudo.","Reparte pollo y queso en las tortillas.","Dóblalas.","Dora por ambos lados."]},
 {id:"x20",title:"Pizza rápida de mozzarella y tomate",image:"/recipe-images/x20.webp",time:25,difficulty:"Fácil",mode:["normal","cocinar"],servings:4,calories:500,protein:21,carbs:65,fat:17,description:"Usa tomate y mozzarella de forma sencilla.",tools:["Horno","Air fryer"],ingredients:[{name:"Masa de pizza",qty:"1 ud",key:"masa"},{name:"Tomate frito",qty:"150 g",key:"tomate"},{name:"Mozzarella",qty:"200 g",key:"mozzarella"}],steps:["Extiende la masa.","Añade tomate y mozzarella.","Hornea hasta que la base esté cocida y el queso fundido.","Sirve."]},
 {id:"x21",title:"Pavo salteado con arroz",image:"/recipe-images/x21.webp",time:25,difficulty:"Fácil",mode:["rapido","mealprep"],servings:4,calories:500,protein:42,carbs:58,fat:11,description:"Alternativa al pollo para varias raciones.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Pechuga de pavo",qty:"650 g",key:"pavo"},{name:"Arroz",qty:"300 g",key:"arroz"},{name:"Verduras variadas",qty:"400 g",key:"verdura"}],steps:["Cuece el arroz.","Saltea el pavo hasta que esté completamente cocinado.","Añade verduras.","Reparte en raciones."]},
 {id:"x22",title:"Entrecot con patata y ensalada",image:"/recipe-images/x22.webp",time:25,difficulty:"Fácil",mode:["normal","cocinar"],servings:2,calories:650,protein:48,carbs:42,fat:31,description:"Para cuando quieres usar un corte de vacuno concreto.",tools:["Placa / inducción","Gas","Air fryer"],ingredients:[{name:"Entrecot",qty:"400 g",key:"entrecot"},{name:"Patatas",qty:"400 g",key:"patata"},{name:"Lechuga",qty:"1 ud",key:"lechuga"}],steps:["Cocina las patatas.","Templa la carne y cocina el entrecot al punto deseado siguiendo prácticas seguras.","Prepara la ensalada.","Sirve junto."]},
 {id:"x23",title:"Solomillo de cerdo con verduras",image:"/recipe-images/x23.webp",time:35,difficulty:"Media",mode:["normal","cocinar"],servings:4,calories:480,protein:43,carbs:28,fat:21,description:"Plato de horno para un corte concreto.",tools:["Horno","Placa / inducción","Gas"],ingredients:[{name:"Solomillo de cerdo",qty:"700 g",key:"solomillo"},{name:"Verduras variadas",qty:"600 g",key:"verdura"}],steps:["Dora el solomillo si quieres.","Añade las verduras.","Termina en horno hasta una cocción segura.","Deja reposar antes de cortar."]},
 {id:"x24",title:"Tofu crujiente con arroz",image:"/recipe-images/x24.webp",time:25,difficulty:"Fácil",mode:["normal","mealprep"],servings:3,calories:460,protein:24,carbs:58,fat:15,description:"Opción vegetal con tofu.",tools:["Air fryer","Placa / inducción","Gas"],ingredients:[{name:"Tofu",qty:"400 g",key:"tofu"},{name:"Arroz",qty:"240 g",key:"arroz"},{name:"Verduras variadas",qty:"350 g",key:"verdura"}],steps:["Seca y corta el tofu.","Dóralo en sartén o air fryer.","Cuece el arroz.","Añade verduras y sirve."]},
 {id:"x25",title:"Pasta con atún y tomate",image:"/recipe-images/x25.webp",time:18,difficulty:"Fácil",mode:["rapido","normal"],servings:4,calories:510,protein:31,carbs:70,fat:11,description:"Despensa pura para un día sin tiempo.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Pasta",qty:"320 g",key:"pasta"},{name:"Atún en lata",qty:"2 uds",key:"atun"},{name:"Tomate frito",qty:"300 g",key:"tomate"}],steps:["Cuece la pasta.","Calienta el tomate.","Escurre el atún.","Mezcla todo."]},
 {id:"x26",title:"Arroz salteado con huevo",image:"/recipe-images/x26.webp",time:20,difficulty:"Fácil",mode:["rapido","normal"],servings:3,calories:430,protein:18,carbs:62,fat:12,description:"Muy útil para aprovechar arroz cocido y verduras.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Arroz",qty:"300 g",key:"arroz"},{name:"Huevos",qty:"3 uds",key:"huevo"},{name:"Verduras variadas",qty:"300 g",key:"verdura"}],steps:["Cocina las verduras.","Cuece el arroz de la lista si está seco y añádelo escurrido a las verduras.","Haz hueco y cuaja el huevo.","Mezcla y sirve."]},
 {id:"x27",title:"Crema de calabaza",image:"/recipe-images/x27.webp",time:35,difficulty:"Fácil",mode:["normal","mealprep"],servings:5,calories:220,protein:6,carbs:36,fat:7,description:"Para convertir bastante verdura en varias raciones.",tools:["Placa / inducción","Gas","Thermomix / robot","Batidora"],ingredients:[{name:"Calabaza",qty:"900 g",key:"calabaza"},{name:"Cebolla",qty:"1 ud",key:"cebolla"},{name:"Patata",qty:"250 g",key:"patata"}],steps:["Trocea las verduras.","Cuece hasta que estén tiernas.","Tritura.","Divide y refrigera o congela lo que no vayas a usar pronto."]},
 {id:"x28",title:"Ensalada de garbanzos",image:"/recipe-images/x28.webp",time:10,difficulty:"Fácil",mode:["rapido","mealprep"],servings:4,calories:390,protein:17,carbs:55,fat:10,description:"Comida fría y fácil para llevar.",ingredients:[{name:"Garbanzos cocidos",qty:"500 g",key:"garbanzo"},{name:"Tomate",qty:"3 uds",key:"tomate"},{name:"Pepino",qty:"1 ud",key:"pepino"},{name:"Cebolla",qty:"1 ud",key:"cebolla"}],steps:["Escurre los garbanzos si son de conserva.","Corta las verduras.","Mezcla.","Aliña al servir."]},
 {id:"x29",title:"Sándwich de pavo, queso y tomate",image:"/recipe-images/x29.webp",time:8,difficulty:"Fácil",mode:["rapido"],servings:2,calories:410,protein:27,carbs:42,fat:15,description:"Para desayunos, cenas o llevar.",ingredients:[{name:"Pan de molde",qty:"4 uds",key:"pan"},{name:"Pechuga de pavo lonchas",qty:"120 g",key:"pavo"},{name:"Queso lonchas",qty:"2 lonchas",key:"queso"},{name:"Tomate",qty:"1 ud",key:"tomate"}],steps:["Corta el tomate.","Monta los sándwiches.","Tuesta si quieres.","Sirve."]},
 {id:"x30",title:"Bowl de arroz, salmón y aguacate",image:"/recipe-images/x30.webp",time:25,difficulty:"Fácil",mode:["normal","mealprep"],servings:3,calories:590,protein:34,carbs:61,fat:23,description:"Un bol completo usando salmón y aguacate.",tools:["Placa / inducción","Gas","Air fryer"],ingredients:[{name:"Salmón",qty:"450 g",key:"salmon"},{name:"Arroz",qty:"240 g",key:"arroz"},{name:"Aguacate",qty:"1 ud",key:"aguacate"}],steps:["Cuece el arroz.","Cocina el salmón hasta que esté hecho.","Corta el aguacate.","Monta los boles."]},
 {id:"x31",title:"Mug cake de chocolate",image:"/recipe-images/x31.webp",time:7,difficulty:"Fácil",mode:["rapido"],servings:1,calories:360,protein:9,carbs:48,fat:15,description:"Postre rápido de chocolate al microondas.",tools:["Microondas"],ingredients:[{name:"Chocolate",qty:"30 g",key:"chocolate"},{name:"Harina",qty:"40 g",key:"harina"},{name:"Leche",qty:"50 ml",key:"leche"},{name:"Huevo",qty:"1 ud",key:"huevo"}],steps:["Mezcla los ingredientes en una taza grande.","Calienta en intervalos cortos hasta que quede cuajado.","Deja reposar un minuto antes de comer."]},
 {id:"x32",title:"Tortitas de chocolate",image:"/recipe-images/x32.webp",time:15,difficulty:"Fácil",mode:["rapido","normal"],servings:2,calories:420,protein:14,carbs:58,fat:15,description:"Desayuno o postre con chocolate, huevo y leche.",tools:["Placa / inducción","Gas"],ingredients:[{name:"Chocolate",qty:"40 g",key:"chocolate"},{name:"Harina",qty:"120 g",key:"harina"},{name:"Leche",qty:"180 ml",key:"leche"},{name:"Huevo",qty:"1 ud",key:"huevo"}],steps:["Mezcla harina, leche y huevo.","Añade el chocolate troceado o fundido.","Cocina porciones pequeñas en sartén.","Sirve calientes."]},
 {id:"x33",title:"Yogur con chocolate y fruta",image:"/recipe-images/x33.webp",time:5,difficulty:"Fácil",mode:["rapido"],servings:1,calories:280,protein:12,carbs:35,fat:10,description:"Postre frío sencillo para aprovechar yogur y chocolate.",ingredients:[{name:"Yogur natural",qty:"1 ud",key:"yogur"},{name:"Chocolate",qty:"25 g",key:"chocolate"},{name:"Fruta",qty:"1 ud",key:"fruta"}],steps:["Pon el yogur en un bol.","Añade fruta troceada.","Ralla o trocea el chocolate por encima.","Sirve frío."]},
 {id:"x34",title:"Brownie sencillo",image:"/recipe-images/x34.webp",time:35,difficulty:"Media",mode:["cocinar"],servings:8,calories:330,protein:6,carbs:42,fat:16,description:"Postre de chocolate para horno con ingredientes básicos.",tools:["Horno"],ingredients:[{name:"Chocolate",qty:"180 g",key:"chocolate"},{name:"Huevos",qty:"3 uds",key:"huevo"},{name:"Harina",qty:"120 g",key:"harina"},{name:"Azúcar",qty:"140 g",key:"azucar"},{name:"Mantequilla",qty:"100 g",key:"mantequilla"}],steps:["Precalienta el horno a 180 °C. Funde el chocolate con la mantequilla.","Mezcla con huevos y azúcar.","Incorpora la harina.","Hornea unos 20–25 minutos hasta que el centro esté cocido y jugoso; deja templar antes de cortar."]},
 {id:"x35",title:"Plátano con chocolate",image:"/recipe-images/x35.webp",time:8,difficulty:"Fácil",mode:["rapido"],servings:2,calories:240,protein:4,carbs:39,fat:9,description:"Postre rápido con fruta y chocolate.",tools:["Microondas"],ingredients:[{name:"Plátano",qty:"2 uds",key:"platano"},{name:"Chocolate",qty:"50 g",key:"chocolate"}],steps:["Corta el plátano.","Funde el chocolate en intervalos cortos.","Reparte por encima.","Sirve al momento o enfría unos minutos."]},
 {id:"x36",title:"Avena con cacao y chocolate",image:"/recipe-images/x36.webp",time:10,difficulty:"Fácil",mode:["rapido","normal"],servings:1,calories:410,protein:14,carbs:58,fat:14,description:"Desayuno dulce o postre de cuchara con avena y chocolate.",tools:["Placa / inducción","Gas","Microondas"],ingredients:[{name:"Avena",qty:"60 g",key:"avena"},{name:"Leche",qty:"250 ml",key:"leche"},{name:"Chocolate",qty:"25 g",key:"chocolate"},{name:"Cacao en polvo",qty:"5 g",key:"cacao"}],steps:["Cuece la avena con la leche.","Añade el cacao y el chocolate al final.","Remueve hasta que se funda.","Sirve caliente."]}
];
