import { normalizeProductText } from "./product-engine";

/** One independently addressable illustration per registered product. */
export const ILLUSTRATED_PRODUCTS = [
  "lechuga iceberg",
  "lechuga romana",
  "lechuga",
  "canónigos",
  "rúcula",
  "espinacas",
  "brócoli",
  "coliflor",
  "tomate cherry",
  "tomate",
  "pepino",
  "calabacín",
  "berenjena",
  "pimiento",
  "zanahoria",
  "cebolla",
  "ajo",
  "patata",
  "boniato",
  "aguacate",
  "champiñón",
  "verduras variadas",
  "fruta",
  "plátano",
  "manzana",
  "pera",
  "naranja",
  "mandarina",
  "limón",
  "fresas",
  "arándanos",
  "frambuesas",
  "uvas",
  "piña",
  "mango",
  "kiwi",
  "melón",
  "sandía",
  "melocotón",
  "fruta del dragón",
  "papaya",
  "maracuyá",
  "granada",
  "lichi",
  "coco",
  "pechuga de pollo",
  "pechuga de pavo",
  "pavo",
  "pechuga",
  "solomillo de pollo",
  "solomillo de pavo",
  "pavo en lonchas",
  "muslo de pollo",
  "pollo entero",
  "pollo",
  "entrecot de vacuno",
  "solomillo de vacuno",
  "filete de ternera",
  "carne picada",
  "hamburguesa de carne",
  "lomo de cerdo",
  "solomillo de cerdo",
  "costillas",
  "secreto de cerdo",
  "presa ibérica",
  "pluma ibérica",
  "cordero",
  "bacon",
  "jamón serrano",
  "jamón cocido",
  "lomo embuchado",
  "chorizo",
  "salchichón",
  "frankfurt",
  "longaniza",
  "salmón",
  "merluza",
  "bacalao",
  "atún fresco",
  "pescado",
  "gambas",
  "mejillones",
  "huevos",
  "mozzarella rallada",
  "mozzarella en bola",
  "mozzarella",
  "queso fresco",
  "queso lonchas",
  "queso rallado",
  "queso curado",
  "queso",
  "yogur",
  "kéfir",
  "mantequilla",
  "nata",
  "leche fresca",
  "leche",
  "tofu",
  "seitán",
  "tempeh",
  "hummus",
  "guacamole",
  "pan de hamburguesa",
  "pan de molde",
  "baguette",
  "pan",
  "croissant",
  "avena",
  "arroz",
  "pasta",
  "harina",
  "azúcar",
  "sal",
  "aceite de oliva",
  "aceite",
  "lentejas",
  "garbanzos",
  "alubias",
  "tomate frito",
  "tomate triturado",
  "atún en lata",
  "conserva",
  "cereales",
  "frutos secos",
  "patatas de bolsa",
  "patatas fritas congeladas",
  "nuggets",
  "verdura congelada",
  "pescado congelado",
  "pollo rebozado congelado",
  "croquetas frescas",
  "croquetas",
  "lasaña fresca",
  "lasaña",
  "pizza fresca",
  "pizza",
  "tortilla preparada",
  "ensalada preparada",
  "sushi",
  "sándwich",
  "barrita de proteína",
  "barrita de chocolate",
  "chocolate con almendras",
  "chocolate con leche",
  "chocolate negro",
  "chocolate",
  "galletas",
  "gominolas",
  "helado",
  "agua",
  "zumo",
  "refresco",
  "bebida energética",
  "café",
  "cerveza",
  "vino",
  "proteína whey",
  "creatina",
  "colágeno",
  "preentreno",
  "vitaminas",
  "detergente lavadora",
  "suavizante",
  "lejía",
  "limpiador multiusos",
  "lavavajillas líquido",
  "pastillas lavavajillas",
  "papel higiénico",
  "papel de cocina",
  "servilletas",
  "bolsas de basura",
  "champú",
  "acondicionador",
  "gel de ducha",
  "jabón de manos",
  "desodorante",
  "pasta de dientes",
  "perfume",
  "crema corporal",
  "crema facial",
  "protector solar",
  "burrata",
  "provolone",
  "raclette",
  "kale",
  "pak choi",
  "yuca",
  "chirivía",
  "nabo",
  "edamame",
  "kimchi",
  "kombucha",
  "tahini",
  "semillas de chía",
  "semillas de lino",
  "soja texturizada",
  "hamburguesa vegetal",
  "salchicha vegetal",
  "proteína vegetal preparada",
  "leche evaporada",
  "leche condensada",
  "focaccia",
  "pan de pita",
  "sriracha",
  "calamares rebozados",
  "queso manchego",
  "queso cheddar",
  "queso gouda",
  "queso edam",
  "queso emmental",
  "queso havarti",
  "queso brie",
  "queso camembert",
  "queso azul",
  "queso de cabra",
  "queso feta",
  "parmesano",
  "ricotta",
  "mascarpone",
  "queso crema",
  "cottage",
  "skyr",
  "yogur griego",
  "yogur natural",
  "yogur bífidus",
  "postre lácteo",
  "chuleta de cerdo",
  "aguja de cerdo",
  "carrillera",
  "carne para guisar",
  "osobuco",
  "chuletón",
  "albóndigas frescas",
  "salchicha fresca",
  "mortadela",
  "fuet",
  "salami",
  "sobrasada",
  "pechuga de pavo lonchas",
  "pollo asado preparado",
  "dorada",
  "lubina",
  "sardinas",
  "boquerones",
  "caballa",
  "trucha",
  "calamar",
  "pulpo",
  "sepia",
  "surimi",
  "judías verdes",
  "guisantes frescos",
  "puerro",
  "apio",
  "alcachofa",
  "espárragos",
  "remolacha",
  "calabaza",
  "maíz dulce",
  "hierbas frescas",
  "ciruela",
  "cereza",
  "higo",
  "caqui",
  "pasta fresca",
  "cuscús",
  "quinoa",
  "bulgur",
  "pan rallado",
  "levadura",
  "maicena",
  "miel",
  "mermelada",
  "crema de cacahuete",
  "ketchup",
  "mayonesa",
  "mostaza",
  "salsa barbacoa",
  "pesto",
  "salsa de soja",
  "vinagre",
  "caldo",
  "cubitos de caldo",
  "especias",
  "muesli",
  "granola",
  "tostadas",
  "tortitas de arroz",
  "cacao soluble",
  "siropes",
  "empanadillas congeladas",
  "varitas de pescado",
  "verduras salteadas congeladas",
  "fruta congelada",
  "gazpacho",
  "crema de verduras preparada",
  "canelones",
  "ensaladilla rusa",
  "tortilla de trigo",
  "leche sin lactosa",
  "bebida de avena",
  "bebida de soja",
  "bebida de almendra",
  "té e infusiones",
  "agua con gas",
  "detergente en polvo",
  "cápsulas de lavadora",
  "quitamanchas",
  "limpiacristales",
  "limpiador de baño",
  "limpiador de suelo",
  "esponjas",
  "film transparente",
  "papel aluminio",
  "bolsas congelación",
  "gel hidroalcohólico",
  "enjuague bucal",
  "cepillo de dientes",
  "hilo dental",
  "algodón",
  "toallitas húmedas",
  "cuchillas de afeitar",
  "espuma de afeitar",
  "sandía rayada",
  "sandía negra",
  "sandía mini",
  "melón amarillo",
  "pipas de girasol",
  "pipas de calabaza",
  "jamón en taquitos",
  "hígado de ave",
  "corazones de pollo",
  "mollejas de pollo",
  "grasa de pato",
  "picantón",
  "pimienta negra",
  "pimienta blanca",
  "pimentón dulce",
  "pimentón picante",
  "vinagre de vino",
  "vinagre de manzana",
  "albahaca",
  "orégano",
  "tomate en rama",
  "tomate pera",
  "tomate rosa",
  "tomate raf",
  "tomate negro",
  "tomate cherry amarillo",
  "aceite de girasol",
  "romero",
  "tomillo",
  "laurel"
] as const;

const index = new Map<string, number>(ILLUSTRATED_PRODUCTS.map((name, i) => [normalizeProductText(name), i]));
const specific: Array<[RegExp, string]> = [
 [/sandia.*negra|black watermelon/, "sandía negra"],
 [/sandia.*rayada|striped watermelon/, "sandía rayada"],
 [/sandia.*mini|mini watermelon/, "sandía mini"],
 [/melon.*amarillo|yellow melon/, "melón amarillo"],
 [/pipas.*girasol|sunflower seeds/, "pipas de girasol"],
 [/pipas.*calabaza|pumpkin seeds/, "pipas de calabaza"],
 [/jamon.*(taquito|taco|dado)|diced cured ham/, "jamón en taquitos"],
 [/higado.*(ave|pollo)|chicken liver/, "hígado de ave"],
 [/corazon.*pollo|chicken hearts/, "corazones de pollo"],
 [/molleja.*pollo|chicken gizzards/, "mollejas de pollo"],
 [/grasa.*pato|duck fat/, "grasa de pato"],
 [/picanton|poussin/, "picantón"],
 [/pimienta.*blanca|white pepper/, "pimienta blanca"],
 [/pimienta|black pepper/, "pimienta negra"],
 [/pimenton.*picante|hot paprika/, "pimentón picante"],
 [/pimenton|paprika/, "pimentón dulce"],
 [/vinagre.*manzana|apple cider vinegar/, "vinagre de manzana"],
 [/vinagre.*vino|wine vinegar/, "vinagre de vino"],
 [/tomate.*cherry.*amarillo|yellow cherry tomato/, "tomate cherry amarillo"],
 [/tomate.*rama|vine tomato/, "tomate en rama"],
 [/tomate.*pera|plum tomato/, "tomate pera"],
 [/tomate.*rosa|pink tomato/, "tomate rosa"],
 [/tomate.*raf/, "tomate raf"],
 [/tomate.*negro|kumato/, "tomate negro"],
 [/aceite.*girasol|sunflower oil/, "aceite de girasol"],
 [/albahaca|basil/, "albahaca"],
 [/oregano/, "orégano"],
 [/romero|rosemary/, "romero"],
 [/tomillo|thyme/, "tomillo"],
 [/laurel|bay leaf/, "laurel"],
];

export function productIllustration(name: string, canonical: string) {
 const normalized = normalizeProductText(name);
 let matched = index.get(normalized);
 if (matched === undefined) {
  const rule = specific.find(([pattern]) => pattern.test(normalized));
  if (rule) matched = index.get(normalizeProductText(rule[1]));
 }
 if (matched === undefined) matched = index.get(normalizeProductText(canonical));
 if (matched === undefined) return null;
 const cell = matched % 16;
 return { name: ILLUSTRATED_PRODUCTS[matched], sheet: Math.floor(matched / 16),
  column: cell % 4, row: Math.floor(cell / 4) };
}
