/** Ingredient varieties and purchase forms; not a live listing of supermarket stock. */
export type ProductVariety={name:string;base:string};
const result:ProductVariety[]=[];
const seen=new Set<string>();
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
function add(name:string,base:string){const key=norm(name);if(!seen.has(key)){seen.add(key);result.push({name,base})}}
function list(base:string,names:string){names.split("|").forEach(n=>add(n.trim(),base))}
function variants(base:string,prefix:string,values:string){values.split("|").forEach(v=>add(prefix+v,base))}
variants("tomate","Tomate ","cherry rojo|cherry amarillo|cherry pera|cherry kumato|cherry en rama|pera|en rama|rosa|Raf|kumato|corazón de buey|Montserrat|de colgar|para ensalada|redondo|verde|amarillo|canario|muchamiel|San Marzano|ibérico|marmande");
variants("manzana","Manzana ","Golden|Gala|Fuji|Pink Lady|Granny Smith|Reineta|Red Delicious|Ambrosia|Envy|Evelina|Kanzi|roja|verde|amarilla");
variants("pera","Pera ","Conferencia|Ercolina|Blanquilla|Williams|Limonera|Comice|Abate|Rocha|de San Juan|Alejandrina");
variants("uvas","Uva ","blanca|roja|negra|blanca sin pepitas|roja sin pepitas|negra sin pepitas|Moscatel|Aledo|Italia|Red Globe|Autumn Royal|Crimson|Cotton Candy");
variants("melón","Melón ","piel de sapo|Cantalupo|Galia|amarillo|blanco|Honeydew|Charentais");
list("sandía","Sandía rayada|Sandía negra|Sandía sin semillas|Sandía mini|Sandía amarilla|Sandía rayada sin semillas|Sandía negra sin semillas");
list("lechuga","Lechuga iceberg|Lechuga romana|Lechuga trocadero|Lechuga batavia|Lechuga hoja de roble|Lechuga lollo rosso|Lechuga lollo biondo|Cogollos de lechuga|Escarola lisa|Escarola rizada|Mezclum|Brotes de lechuga");
list("patata","Patata nueva|Patata vieja|Patata roja|Patata blanca|Patata agria|Patata monalisa|Patata Kennebec|Patata para freír|Patata para cocer|Patata para asar|Patata baby|Patata violeta|Patata lavada|Patata sin lavar");
list("cebolla","Cebolla blanca|Cebolla morada|Cebolla dulce|Cebolla de Figueres|Cebolla tierna|Cebolleta|Chalota|Cebolla para encurtir");
list("pimiento","Pimiento rojo|Pimiento verde|Pimiento amarillo|Pimiento naranja|Pimiento italiano|Pimiento de Padrón|Pimiento del piquillo fresco|Pimiento lamuyo|Pimiento mini|Guindilla fresca");
list("champiñón","Champiñón blanco|Champiñón portobello|Champiñón laminado|Champiñón entero|Champiñón baby");
list("setas","Seta de ostra|Setas shiitake|Setas shimeji|Setas enoki|Boletus|Níscalos|Rebozuelos|Trompetas de la muerte|Mezcla de setas");
list("naranja","Naranja Navel|Naranja Navelina|Naranja Valencia|Naranja sanguina|Naranja para zumo|Naranja de mesa");
list("mandarina","Mandarina clementina|Mandarina Nadorcott|Mandarina Orri|Mandarina Satsuma|Mandarina Clemenules");
list("kiwi","Kiwi verde|Kiwi amarillo|Kiwi rojo|Kiwi baby");
list("melocotón","Melocotón amarillo|Melocotón rojo|Melocotón blanco|Melocotón de Calanda|Paraguayo blanco|Paraguayo amarillo|Nectarina amarilla|Nectarina blanca|Platerina");
list("aguacate","Aguacate Hass|Aguacate Fuerte|Aguacate Bacon|Aguacate maduro|Aguacate para madurar");
list("calabaza","Calabaza cacahuete|Calabaza potimarrón|Calabaza redonda|Calabaza pelada|Calabaza en dados");
list("calabacín","Calabacín verde|Calabacín blanco|Calabacín amarillo|Calabacín redondo|Calabacín mini");
list("berenjena","Berenjena negra|Berenjena rayada|Berenjena blanca|Berenjena redonda");
list("col","Col blanca|Col lombarda|Col rizada|Col china|Pak choi|Col de Bruselas|Kale");
list("fruta","Papaya|Pitahaya roja|Pitahaya amarilla|Maracuyá|Granadilla|Lichi|Chirimoya|Caqui persimon|Caqui clásico|Higo negro|Higo verde|Breva|Ciruela roja|Ciruela amarilla|Ciruela negra|Albaricoque|Níspero|Pomelo rosa|Pomelo blanco|Lima|Membrillo|Grosella roja|Grosella negra|Mora|Frambuesa|Arándano|Fresón|Fresa|Granada|Coco|Piña tropical|Mango listo para comer|Plátano de Canarias|Banana|Plátano macho");
list("verduras variadas","Acelga verde|Acelga roja|Apio verde|Apio blanco|Hinojo fresco|Nabo blanco|Nabo amarillo|Chirivía|Rábano rojo|Rábano blanco|Daikon|Colinabo|Borraja|Cardo|Endibia|Achicoria|Judía verde plana|Judía verde redonda|Tirabeques|Guisantes frescos|Habas frescas|Espárrago verde fino|Espárrago verde grueso|Espárrago blanco fresco|Alcachofa fresca|Romanesco|Brotes de soja|Brotes de alfalfa");
for(const [animal,cuts] of [
 ["pollo","pechuga|pechuga en filetes|pechuga en dados|solomillo|muslo|contramuslo|contramuslo deshuesado|alitas|jamoncitos|cuartos traseros|carcasa|cuello|hígado|corazones|mollejas|carne picada|entero|medio"],
 ["pavo","pechuga|pechuga en filetes|solomillo|muslo|contramuslo|alitas|carne picada|entero"],
 ["ternera","filete|entrecot|chuletón|solomillo|redondo|babilla|tapa|contra|aguja|falda|morcillo|ossobuco|carne picada|carne para guisar|costilla|hígado|lengua|rabo|callos|carrillera"],
 ["cerdo","lomo|lomo en filetes|solomillo|secreto|presa|pluma|carrillera|panceta|costilla|chuleta|aguja|magro para guisar|carne picada|codillo|manitas|oreja|morro|hígado|espinazo"],
 ["cordero","pierna|paletilla|chuletas|costillar|cuello|falda|carne para guisar|riñones|mollejas"],
 ["conejo","entero|troceado|piernas|paletillas|hígado"],
 ["pato","magret|muslos|entero|grasa|hígado"]
] as const)for(const cut of cuts.split("|"))add(cut.charAt(0).toUpperCase()+cut.slice(1)+" de "+animal,animal==="ternera"?"filete de ternera":animal==="cerdo"?"lomo de cerdo":animal==="cordero"?"cordero":animal==="pato"?"pato":animal);
for(const species of ["Salmón","Merluza","Bacalao","Dorada","Lubina","Rape","Lenguado","Trucha","Atún","Bonito","Sardina","Caballa","Boquerón","Besugo","Gallo","Rodaballo","Corvina","Pescadilla"])for(const form of ["fresco","en filetes","en lomos","congelado"])add(species+" "+form,form==="congelado"?"pescado congelado":species);
for(const shell of ["Gambas","Langostinos","Camarones","Calamares","Sepia","Pulpo","Mejillones","Almejas","Berberechos","Vieiras"])for(const form of ["frescos","congelados","cocidos"])add(shell+" "+form,form==="congelados"?"pescado congelado":form==="cocidos"?"marisco cocido":shell);
for(const deli of ["Jamón serrano","Jamón ibérico","Jamón cocido","Lacón","Pechuga de pavo en fiambre","Chorizo","Salchichón","Lomo embuchado","Fuet","Cecina","Mortadela","Bacon"])for(const form of ["en lonchas","en taquitos","al corte"])add(deli+" "+form,deli);
const cheeses=["Manchego","Gouda","Edam","Emmental","Havarti","Cheddar","Maasdam","Gruyère","Comté","Parmesano","Grana Padano","Pecorino","Gorgonzola","Roquefort","Cabrales","Danablu","Brie","Camembert","Reblochon","Taleggio","Feta","Halloumi","Mozzarella","Burrata","Ricotta","Mascarpone","Cottage","Quark","de Burgos","de cabra","de oveja","de vaca","mezcla","Tetilla","Arzúa-Ulloa","San Simón","Idiazábal","Roncal","Mahón","Zamorano","Majorero","Palmero","Murcia al vino","Torta del Casar","La Serena","Caciocavallo","Provolone","Oaxaca","azul","crema"];
for(const cheese of cheeses)add("Queso "+cheese,"queso");
for(const cheese of ["Manchego","Gouda","Edam","Emmental","Havarti","Cheddar","Maasdam","Gruyère","Comté","Parmesano","Grana Padano","Pecorino","de cabra","de oveja","de vaca","mezcla","Idiazábal","Roncal","Mahón","Zamorano"])for(const form of ["en lonchas","en cuña","rallado","en dados"])add("Queso "+cheese+" "+form,form==="rallado"?"queso rallado":form==="en lonchas"?"queso en lonchas":"queso");
for(const animal of ["vaca","cabra","oveja","mezcla"])for(const age of ["tierno","semicurado","curado","viejo"])add("Queso de "+animal+" "+age,"queso");
for(const dairy of ["Yogur natural","Yogur griego","Yogur desnatado","Yogur sin lactosa","Skyr","Kéfir"])for(const flavour of ["sin azúcar","de fresa","de plátano","de limón","de vainilla","de coco","de mango","de frutos del bosque","con melocotón","con piña"])add(dairy+" "+flavour,dairy==="Kéfir"?"kéfir":"yogur natural");
for(const milk of ["entera","semidesnatada","desnatada"])for(const form of ["UHT","fresca","sin lactosa","de cabra"])add("Leche "+milk+" "+form,form==="fresca"?"leche fresca":"leche");
for(const plant of ["avena","soja","almendra","arroz","coco","avellana"])for(const form of ["sin azúcar","barista","con calcio","con cacao"])add("Bebida de "+plant+" "+form,"bebida vegetal");
for(const shape of ["Espaguetis","Macarrones","Penne","Fusilli","Farfalle","Rigatoni","Tallarines","Fettuccine","Tagliatelle","Linguine","Bucatini","Conchiglie","Orecchiette","Fideos finos","Fideos gruesos","Estrellitas","Letras","Galets","Placas de lasaña","Canelones","Orzo","Ditalini"])for(const kind of ["de trigo","integrales","sin gluten"])add(shape+" "+kind,"pasta");
for(const filling of ["queso","carne","espinacas y ricotta","setas","jamón","calabaza"])for(const shape of ["Raviolis","Tortellini"])add(shape+" frescos de "+filling,"pasta fresca");
for(const grain of ["largo","redondo","basmati","jazmín","bomba","integral","vaporizado","salvaje","Arborio","Sushi"])add("Arroz "+grain,"arroz");
for(const grain of ["basmati","integral","largo","redondo"])add("Arroz "+grain+" cocido","arroz cocido");
for(const bean of ["Lentejas pardinas","Lentejas castellanas","Lentejas rojas","Lentejas verdes","Garbanzos pedrosillanos","Garbanzos lechosos","Garbanzos castellanos","Alubias blancas","Alubias rojas","Alubias negras","Alubias pintas","Alubias de Tolosa","Judiones","Soja amarilla","Soja verde"])for(const state of ["secos","cocidos en bote"])add(bean+" "+state,state==="secos"?"legumbres secas":"legumbres cocidas");
for(const fish of ["Atún","Bonito","Caballa","Sardinas","Sardinillas","Mejillones","Berberechos","Navajas","Calamares","Pulpo"])for(const preparation of ["al natural","en aceite de oliva","en aceite de girasol","en escabeche"])add(fish+" en conserva "+preparation,"conserva de pescado");
list("pan","Pan blanco|Pan integral|Pan multicereal|Pan de centeno|Pan de espelta|Pan de avena|Pan de semillas|Pan de masa madre|Pan de molde blanco|Pan de molde integral|Pan de molde sin corteza|Baguette|Chapata|Pan rústico|Pan de pueblo|Pan de cristal|Mollete|Pan de pita|Pan naan|Pan de hamburguesa|Pan brioche de hamburguesa|Pan de perrito|Tortillas de trigo|Tortillas de maíz|Tostadas integrales|Regañás|Picos de pan|Colines|Pan sin gluten");
list("harina","Harina de trigo|Harina integral de trigo|Harina de fuerza|Harina de repostería|Harina de espelta|Harina de centeno|Harina de avena|Harina de maíz|Harina de arroz|Harina de garbanzo|Harina de almendra|Sémola de trigo|Almidón de maíz|Almidón de patata|Tapioca|Pan rallado fino|Pan rallado grueso|Panko");
list("frutos secos","Almendras crudas|Almendras tostadas|Almendras laminadas|Almendras molidas|Nueces peladas|Nueces con cáscara|Avellanas crudas|Avellanas tostadas|Anacardos crudos|Anacardos tostados|Pistachos tostados|Pistachos pelados|Cacahuetes tostados|Cacahuetes crudos|Cacahuetes con cáscara|Piñones|Nueces pecanas|Nueces de macadamia|Coquitos|Mezcla de frutos secos|Pipas de girasol con cáscara|Pipas de girasol peladas|Pipas de calabaza|Semillas de chía|Semillas de lino|Sésamo blanco|Sésamo negro|Semillas de cáñamo");
list("especias","Sal fina|Sal gruesa|Sal marina|Sal yodada|Sal en escamas|Pimienta negra en grano|Pimienta negra molida|Pimienta blanca|Pimienta verde|Pimienta rosa|Pimentón dulce|Pimentón picante|Pimentón ahumado|Comino molido|Comino en grano|Cúrcuma|Curry suave|Curry picante|Garam masala|Ras el hanout|Canela molida|Canela en rama|Jengibre molido|Jengibre fresco|Nuez moscada|Clavo|Cardamomo|Anís estrellado|Azafrán|Colorante alimentario|Orégano seco|Albahaca seca|Tomillo seco|Romero seco|Laurel seco|Eneldo seco|Perejil seco|Cilantro seco|Ajo en polvo|Cebolla en polvo|Cayena|Chile en copos|Sazonador de pollo|Sazonador de pescado|Sazonador de carne|Sazonador de verduras|Sazonador de patatas|Hierbas provenzales");
list("aceite de oliva","Aceite de oliva virgen extra|Aceite de oliva virgen|Aceite de oliva suave|Aceite de oliva intenso|Aceite de oliva arbequina|Aceite de oliva picual|Aceite de oliva hojiblanca|Aceite de oliva cornicabra");
list("aceite de girasol","Aceite de girasol|Aceite de girasol alto oleico");
list("vinagre","Vinagre de vino blanco|Vinagre de vino tinto|Vinagre de manzana|Vinagre de Jerez|Vinagre balsámico|Vinagre de arroz|Crema balsámica");
list("salsas","Tomate frito|Tomate triturado|Tomate entero pelado|Tomate concentrado|Salsa de tomate y albahaca|Pesto verde|Pesto rojo|Salsa boloñesa|Salsa napolitana|Salsa de queso|Salsa de champiñones|Mayonesa|Mayonesa ligera|Alioli|Mostaza de Dijon|Mostaza antigua|Mostaza dulce|Ketchup|Salsa barbacoa|Salsa de soja|Salsa teriyaki|Salsa de ostras|Sriracha|Tabasco|Salsa picante|Salsa de yogur|Salsa César|Salsa de curry|Salsa brava|Salsa romesco|Tahini|Chimichurri|Salsa holandesa|Salsa bechamel");
list("bebida","Agua mineral sin gas|Agua mineral con gas|Agua con limón|Zumo de naranja|Zumo de manzana|Zumo de piña|Zumo de melocotón|Zumo de tomate|Néctar de mango|Néctar de pera|Café molido natural|Café molido mezcla|Café en grano|Café soluble|Café descafeinado|Café en cápsulas|Té negro|Té verde|Té rojo|Té blanco|Manzanilla|Poleo menta|Rooibos|Tila|Infusión de jengibre|Infusión de frutos rojos|Cola|Cola sin azúcar|Refresco de naranja|Refresco de limón|Tónica|Tónica sin azúcar|Gaseosa|Bebida isotónica|Bebida energética|Cerveza rubia|Cerveza tostada|Cerveza sin alcohol|Cerveza sin gluten|Vino tinto|Vino blanco|Vino rosado|Cava brut|Cava semiseco|Sidra|Mosto");
list("snack","Patatas de bolsa lisas|Patatas de bolsa onduladas|Patatas de bolsa al punto de sal|Patatas de bolsa sabor jamón|Patatas de bolsa sabor queso|Patatas de bolsa sabor barbacoa|Patatas de bolsa sabor vinagre|Nachos de maíz|Nachos de queso|Palomitas saladas|Palomitas dulces|Gusanitos de maíz|Cortezas de cerdo|Tortitas de arroz|Tortitas de maíz|Crackers integrales|Crackers salados|Pretzels|Aceitunas verdes|Aceitunas negras|Aceitunas rellenas de anchoa|Pepinillos|Alcaparras|Banderillas|Chocolate negro 70%|Chocolate negro 85%|Chocolate negro 90%|Chocolate con leche|Chocolate blanco|Chocolate con almendras|Chocolate con avellanas|Chocolate con naranja|Galletas María|Galletas integrales|Galletas de avena|Galletas de mantequilla|Galletas de chocolate|Cookies con pepitas|Barquillos|Bizcochos de soletilla|Magdalenas|Croissants|Napolitanas de chocolate|Donuts|Brownie|Bizcocho de limón|Bizcocho de chocolate|Turrón de Jijona|Turrón de Alicante|Mazapán|Polvorones|Mantecados");
for(const name of ["Brócoli","Coliflor","Espinacas","Judías verdes","Guisantes","Habas","Zanahoria","Alcachofas","Menestra","Verduras para wok","Frutos rojos","Fresas","Mango","Piña"])add(name+" congelados","verduras congeladas");
for(const filling of ["jamón","pollo","bacalao","setas","cocido","queso"])add("Croquetas congeladas de "+filling,"croquetas congeladas");
for(const filling of ["margarita","cuatro quesos","barbacoa","jamón y queso","pepperoni","vegetal","atún","pollo"])add("Pizza congelada "+filling,"pizza congelada");
for(const flavour of ["vainilla","chocolate","fresa","nata","limón","mango","pistacho","café"])add("Helado de "+flavour,"helado");
list("gominolas","Mentos menta|Mentos frutas|Chupa Chups fresa|Chupa Chups cola|Gominolas de ositos|Gominolas de regaliz|Caramelos sin azúcar");
list("magdalenas","Magdalenas tradicionales|Magdalenas de chocolate|Magdalenas integrales");
list("valencianas","Valencianas");
list("ensaimadas","Ensaimada lisa|Ensaimada de cabello de ángel|Ensaimada de crema");
export const PRODUCT_VARIETIES=result;
export const PRODUCT_VARIETY_INDEX=new Map(result.map(v=>[norm(v.name),v]));
export function findProductVariety(name:string){const n=norm(name);return PRODUCT_VARIETY_INDEX.get(n)}
