import type {RecipeEntry} from "./extra-recipes";
const ingredients=(items:[string,string][])=>items.map(([name,qty])=>({name,qty,key:name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}));
const fillings:[string,[string,string][],number,number,number][]=[
 ["aguacate y pepino",[["Aguacate","160 g"],["Pepino","160 g"]],7,58,9],
 ["zanahoria y pepino",[["Zanahoria","160 g"],["Pepino","160 g"]],5,59,2],
 ["langostinos cocidos y aguacate",[["Langostinos cocidos","200 g"],["Aguacate","160 g"]],18,57,10],
 ["salmón cocinado y pepino",[["Salmón","240 g"],["Pepino","160 g"]],19,57,10],
 ["tofu y pepino",[["Tofu","240 g"],["Pepino","160 g"]],15,58,7],
 ["tortilla y aguacate",[["Huevos","4 uds"],["Aguacate","160 g"]],14,57,14]
];
export const THEME_RECIPES:RecipeEntry[]=fillings.map(([filling,items,protein,carbs,fat],index)=>({
 id:"theme-sushi-"+index,title:"Maki casero de "+filling,image:"/recipe-images/theme-sushi.webp",photoCaption:index===0?"Imagen generada de esta receta":"Foto orientativa de maki vegetal · el relleno de esta receta es diferente",time:40,difficulty:"Media",mode:["cocinar","normal"],servings:4,calories:protein*4+carbs*4+fat*9,protein,carbs,fat,family:"sushi",mealTypes:["Comida","Cena"],tools:["Placa / inducción","Gas"],description:"Inspiración japonesa con relleno vegetal o cocinado. Prepara para comer en el momento; no es una tanda para siete días.",
 ingredients:ingredients([["Arroz para sushi","280 g"],["Alga nori","4 hojas"],["Vinagre de arroz","40 ml"],["Azúcar","12 g"],["Sal","2 g"],...items]),
 steps:["Lava el arroz hasta que el agua salga más clara. Cuécelo con el agua y tiempo que indique su envase, deja reposar tapado y pasa a una fuente limpia.","Disuelve el azúcar y la sal en el vinagre. Incorpora suavemente al arroz y deja templar para poder manipularlo.",index===3?"Cocina completamente el salmón y desmenúzalo. Lava el pepino y córtalo en tiras.":index===5?"Bate los huevos y haz una tortilla bien cuajada por ambos lados. Córtala en tiras con el aguacate.":index===4?"Escurre el tofu y cocínalo en tiras siguiendo el envase. Lava y corta el pepino.":"Prepara los rellenos: lava las verduras, corta en tiras y, si usas langostinos ya cocidos, comprueba el envase y mantenlos refrigerados hasta montar.","Pon el nori sobre una esterilla cubierta con film alimentario. Extiende arroz con manos limpias ligeramente húmedas, deja un borde libre, coloca el relleno y enrolla con cuidado.","Corta con cuchillo limpio húmedo y sirve enseguida. Si esperas para servir, refrigera y evita dejar el arroz a temperatura ambiente; sigue la conservación indicada en los ingredientes."]
}));
for(const [index,proteinName,proteinQty,p,c,f] of [[0,"Carne picada de ternera","300 g",35,55,26],[1,"Pechuga de pollo","320 g",43,55,14],[2,"Hamburguesas vegetales","2 uds",23,66,18],[3,"Carne picada de cerdo","300 g",32,55,29]] as const){
 THEME_RECIPES.push({id:"theme-burger-"+index,title:"Hamburguesa de "+["ternera con cheddar y pepinillos","pollo con lechuga y tomate","vegetales con aguacate","cerdo con cebolla dorada"][index],image:"/recipe-images/r1.webp",photoCaption:"Foto orientativa de la familia de hamburguesas",time:25,difficulty:"Fácil",mode:["normal","cocinar"],servings:2,protein:p,carbs:c,fat:f,calories:p*4+c*4+f*9,family:"hamburguesa",mealTypes:["Comida","Cena"],tools:["Placa / inducción","Gas"],description:"Versión casera inspirada en las hamburguesas americanas; revisa los ingredientes que realmente vas a usar.",ingredients:ingredients([[proteinName,proteinQty],["Pan de hamburguesa","2 uds"],...(index===0?[["Queso cheddar","40 g"],["Pepinillos","40 g"]] as [string,string][]:index===2?[["Aguacate","100 g"],["Tomate","100 g"]] as [string,string][]:index===3?[["Cebolla","120 g"],["Aceite de oliva","10 ml"]] as [string,string][]:[["Lechuga","40 g"],["Tomate","100 g"]] as [string,string][])]),steps:["Lava y corta los vegetales. Si usas cebolla, dórala con el aceite a fuego medio.",index===2?"Cocina las hamburguesas vegetales siguiendo el envase.":index===1?"Corta el pollo en dos filetes y cocínalo completamente en la sartén, también en el centro.":"Forma dos hamburguesas con la carne picada y cocínalas completamente por ambos lados, comprobando el centro.","Tuesta ligeramente el pan y añade el queso o las verduras indicadas.","Monta y sirve al momento. Si cambias un ingrediente, indícalo antes de confirmar el consumo."]});
}
