import assert from 'node:assert/strict';
import {quickStockChoices,speechErrorMessage} from '../lib/quick-stock';
import {splitShoppingEntries,shoppingInputNeedsReview} from '../lib/shopping-input';
import {freshnessNotice} from '../lib/household-reading';
import {themeForMonth} from '../lib/recipe-themes';
assert.deepEqual(quickStockChoices('Huevos ecológicos','uds').map(x=>x.qty),[6,12,24]);
assert.ok(quickStockChoices('Huevos','pack').every(x=>x.unit==='pack'));
assert.deepEqual(quickStockChoices('Banana','ud')[0],{qty:1,unit:'racimos',label:'1 racimo'});
assert.equal(quickStockChoices('Plátano de Canarias','kg')[0].unit,'kg');
assert.equal(quickStockChoices('Queso','g')[1].qty,250);
assert.equal(quickStockChoices('Pan integral','ud')[1].qty,2);
assert.equal(quickStockChoices('Leche','L')[0].unit,'L');
assert.match(speechErrorMessage('network'),/no conecta/);
assert.match(speechErrorMessage('not-allowed'),/bloqueado/);
assert.match(speechErrorMessage('audio-capture'),/micrófono/);
const phrase='Quiero comprar ketchup para hacer macarrones con tomate y también para luego para cenar lomo adobado con patatas';
assert.equal(shoppingInputNeedsReview(phrase),false);
assert.deepEqual(splitShoppingEntries('Quiero comprar ketchup para hacer macarrones con tomate'),['ketchup','macarrones','tomate']);
assert.ok(splitShoppingEntries(phrase).some(x=>x==='lomo adobado'));
assert.ok(splitShoppingEntries(phrase).some(x=>x==='patatas'));
assert.equal(shoppingInputNeedsReview('Eso lo has escrito mal y no lo borres'),true);
assert.equal(themeForMonth(new Date('2026-10-09T12:00:00')).title,'Pizzas del mundo');
assert.notEqual(themeForMonth(new Date('2026-10-09T12:00:00')).id,themeForMonth(new Date('2026-11-09T12:00:00')).id);
const x={name:'Yogur',qty:1,stock:'hay',location:'Nevera',estimatedExpires:'2026-10-10'};
assert.equal(freshnessNotice(x,null,'2026-10-09')?.text,'Podría caducar pronto · fecha estimada');
assert.match(freshnessNotice(x,null,'2026-10-11')!.text,/plazo estimado/);
assert.ok(!/Caduca mañana/.test(freshnessNotice(x,null,'2026-10-09')!.text));
console.log('PASS: clear UI quantities, unit integrity, speech errors, long requests, monthly themes and estimated dates');
