import assert from 'node:assert/strict';
import {estimateConsumption,estimateInventoryConsumption,shoppingQuantityStep,changeShoppingQuantity} from '../lib/consumption-engine';
import {matchesRecipeSearch} from '../lib/catalog-search';
import {normalizeSupermarket} from '../lib/supermarkets';
import {shoppingInputNeedsReview,splitShoppingEntries,parseShoppingQuantity} from '../lib/shopping-input';
import {productSuggestions} from '../lib/product-engine';
import {RECIPES} from '../lib/recipes';
const milk={name:'Leche',qty:3,unit:'L',category:'Lácteos',purchasedAt:'2026-10-01',estimateAnchorDate:'2026-10-01',estimateAnchorQty:1,location:'Despensa'};
const buys=[{name:'Leche',qty:1,unit:'L',date:'2026-09-17'},{name:'Leche',qty:1000,unit:'ml',date:'2026-09-24'},{name:'Leche',qty:1,unit:'L',date:'2026-10-01'}];
const weekly=estimateConsumption(milk,buys,[],[],'2026-10-08');
assert.equal(weekly.source,'purchases');assert.equal(weekly.estimatedQty,0);assert.equal(milk.qty,3,'estimating never mutates recorded stock');assert.ok(Math.abs(weekly.dailyRate-1/7)<1e-9);
const doubled=estimateConsumption({...milk,estimateAnchorQty:2},buys,[],[],'2026-10-08');assert.equal(doubled.estimatedQty,1,'two litres last longer than one');
assert.equal(estimateConsumption({...milk,location:'Congelador'},buys,[],[],'2026-11-08').estimatedQty,1,'freezer does not use daily consumption');
assert.equal(estimateConsumption({...milk,storageMode:'reserva'},buys,[],[],'2026-11-08').estimatedQty,1,'reserves do not silently disappear');
assert.equal(estimateConsumption(milk,[],[],[],'2026-10-08').source,'unknown');
const habits=[{id:'h',name:'Leche',qty:1,unit:'L',days:7}];assert.equal(estimateConsumption(milk,[],habits,[],'2026-10-08').source,'habit');
const checks=[{id:'a',name:'Leche',qty:1,unit:'L',date:'2026-09-24',location:'Todo'},{id:'b',name:'Leche',qty:1,unit:'L',date:'2026-10-01',location:'Todo'}];
const adjusted=estimateConsumption(milk,buys,habits,checks,'2026-10-08');assert.equal(adjusted.source,'confirmed');assert.ok(Math.abs(adjusted.dailyRate-1/7)<1e-9);
const accumulates=[checks[0],{...checks[1],qty:2}];const noUse=estimateConsumption(milk,buys,habits,accumulates,'2026-10-08');assert.equal(noUse.dailyRate,0,'buying while stock grows is not consumption');assert.equal(noUse.estimatedQty,1);
const onlyLocation=checks.map(c=>({...c,location:'Nevera'}));assert.equal(estimateConsumption(milk,[],habits,onlyLocation,'2026-10-08').source,'habit','moving a location is not evidence of consumption');
assert.equal(estimateConsumption(milk,[...buys.map(b=>({...b,unit:'bricks'}))],[],[],'2026-10-08').source,'unknown','do not assume a brick equals a litre');
assert.equal(estimateConsumption(milk,[...buys,...buys.map(b=>({...b,date:'2027-01-01'}))],[],[],'2026-10-08').estimatedQty,0,'future data ignored');
for(const [unit,step] of [['g',10],['ml',10],['kg',.1],['L',.1],['uds',1]] as const)assert.equal(shoppingQuantityStep(unit),step);
for(const [input,out] of [['mercdona','Mercadona'],['MERCADONA','Mercadona'],['bonaria','BonÀrea'],['bonarea','BonÀrea'],['lidll','Lidl'],['esclat','Esclat'],['Tienda de Ana','Tienda de Ana']])assert.equal(normalizeSupermarket(input),out);
const sample={title:'Huevos fritos con arroz',country:'España',ingredients:[{name:'Huevos'},{name:'Arroz'}]};
for(const q of ['ous','ou ferrat','fried eggs','rice','Spain','huevos arroz'])assert.ok(matchesRecipeSearch(sample,q),q);
assert.ok(!matchesRecipeSearch(sample,'chicken'));assert.ok(!matchesRecipeSearch({title:'Pasta',ingredients:[]},'pa'),'short synonym cannot match inside pasta');
assert.ok(RECIPES.filter(r=>matchesRecipeSearch(r,'pa amb tomàquet')).length>0);
assert.ok(RECIPES.filter(r=>matchesRecipeSearch(r,'Japan')).length>=6);
assert.equal(changeShoppingQuantity(1,'g',-1),1);assert.equal(changeShoppingQuantity(90,'g',-1),80);assert.equal(changeShoppingQuantity(1,'uds',-1),1);assert.equal(changeShoppingQuantity(2,'L',-1),1.9);
assert.ok(shoppingInputNeedsReview('Vale pero todo esto lo has escrito mal hemos puesto el ketchup pero lo otro no se tiene que ir'));assert.ok(shoppingInputNeedsReview('quita ketchup'));assert.ok(!shoppingInputNeedsReview('leche, 2 yogures y 1 kg de pollo'));
assert.equal(splitShoppingEntries('Necesito pasta para macarrones y ketchup')[0],'macarrones');assert.equal(parseShoppingQuantity('1 kg de pollo').unit,'kg');
assert.deepEqual(splitShoppingEntries('Necesito comprar ketchup para hacer macarrones con tomate, también para luego para cenar lomo adobado con patatas'),['ketchup','macarrones','tomate','lomo adobado','patatas'],'voice phrases keep every food and remove conversational glue');
assert.ok(productSuggestions('pescado').length>=5);assert.ok(productSuggestions('carne').length>=3);assert.ok(productSuggestions('pechuga').length>=2);
console.log('PASS: consumo semanal, acumulación, cantidades, unidades, congelador, reservas, confirmaciones, idiomas, tiendas y conversaciones');

const twoLocations=[{...milk,qty:1,estimateAnchorQty:1,location:'Despensa'},{...milk,qty:1,estimateAnchorQty:1,location:'Nevera'}];
const split=twoLocations.map(i=>estimateInventoryConsumption(i,twoLocations,buys,[],[],'2026-10-08'));assert.ok(Math.abs(split.reduce((n,x)=>n+x.dailyRate,0)-1/7)<1e-9);assert.equal(split.reduce((n,x)=>n+x.estimatedQty,0),1,'household rate is only applied once across two locations');
