import {estimateInventoryConsumption} from '../lib/consumption-engine';
import assert from 'node:assert/strict';
import {freshnessNotice,stockCoverage} from '../lib/household-reading';
const today='2026-10-09';
const meat={qty:1,stock:'hay',location:'Nevera',expires:'2026-10-14',dateType:'caducidad'};
const before=JSON.stringify(meat);
assert.equal(freshnessNotice(meat,21,today)?.kind,'slow');
assert.equal(freshnessNotice(meat,3,today),null);
assert.equal(freshnessNotice({...meat,storageMode:'reserva'} as typeof meat,21,today)?.kind,'slow');
assert.equal(freshnessNotice({...meat,location:'Congelador'},21,today),null);
assert.equal(freshnessNotice({...meat,expires:'2026-10-08'},21,today)?.kind,'expired');
assert.equal(freshnessNotice({...meat,expires:'2026-10-08',dateType:'preferente'},21,today)?.kind,'quality');
assert.equal(freshnessNotice({...meat,expires:'2026-10-09'},21,today)?.text,'Caduca hoy');
assert.equal(freshnessNotice({...meat,expires:'2026-10-10'},21,today)?.text,'Caduca mañana');
assert.equal(freshnessNotice({...meat,qty:0},21,today),null);
assert.equal(freshnessNotice({...meat,stock:'falta'},21,today),null);
assert.equal(freshnessNotice({...meat,expires:'2026-02-31'},21,today),null);
assert.equal(freshnessNotice({...meat,expires:undefined,estimatedExpires:'2026-10-08'},21,today)?.kind,'estimate');
assert.equal(freshnessNotice({...meat,expires:undefined},21,today),null);
assert.equal(freshnessNotice({...meat,location:'Congelador',qualityReviewAt:'2026-10-09'},21,today)?.kind,'quality');
assert.equal(stockCoverage(null,'unknown').tone,'learn');
assert.equal(stockCoverage(1,'unknown').tone,'learn');
assert.equal(stockCoverage(1,'habit').tone,'low');
assert.equal(stockCoverage(10,'habit').tone,'steady');
assert.equal(stockCoverage(30,'habit').tone,'plenty');
assert.equal(stockCoverage(30,'habit',30).tone,'steady');
assert.equal(stockCoverage(Infinity,'habit').tone,'learn');
assert.equal(JSON.stringify(meat),before);
const item={...meat,name:'Pechuga de pollo',category:'Carne',unit:'kg',purchasedAt:today};
const estimate=estimateInventoryConsumption(item,[item],[],[{id:'h',name:item.name,qty:1,unit:'kg',days:21}],[],today);
assert.equal(freshnessNotice(item,estimate.daysLeft,today)?.kind,'slow');
assert.equal(freshnessNotice({...item,expires:undefined,purchasedAt:'2026-10-06'},null,today)?.kind,'estimate');
assert.equal(freshnessNotice({...item,expires:undefined,purchasedAt:'2026-10-06',purchaseDateUnknown:true},null,today),null);
console.log('PASS: 25 household reading checks (dates, reserves, freezer, estimates, coverage, immutability)');
