import assert from 'node:assert/strict';
import {interpretShoppingRequest,parseShoppingQuantity,shoppingInputNeedsReview} from '../lib/shopping-input';
import {interpretHouseholdNote,weeklyBudgetToMonthly} from '../lib/household-language';
import {normalizeSupermarket} from '../lib/supermarkets';
import {quickStockChoices} from '../lib/quick-stock';
const mixed=interpretShoppingRequest('Necesito ir al supermercado a comprar leche, huevos y luego a meter en la nevera pasta con macarrones y tomate');
assert.deepEqual(mixed.shopping,['leche','huevos']);assert.equal(mixed.home[0].kind,'prepared');assert.equal(mixed.home[0].name,'pasta con macarrones y tomate');assert.equal(mixed.home[0].location,'Nevera');
assert.deepEqual(interpretShoppingRequest('Necesito comprar ketchup para hacer macarrones con tomate, también para luego para cenar lomo adobado con patatas').shopping,['ketchup','macarrones','tomate','lomo adobado','patatas']);
assert.deepEqual(parseShoppingQuantity('dos briks de leche'),{name:'leche',qty:2,unit:'bricks'});
assert.deepEqual(parseShoppingQuantity('leche'),{name:'leche',qty:1,unit:'bricks'});
assert.deepEqual(parseShoppingQuantity('2 litros de leche'),{name:'leche',qty:2,unit:'L'});
assert.deepEqual(parseShoppingQuantity('medio kilo de pollo'),{name:'pollo',qty:.5,unit:'kg'});
assert.deepEqual(parseShoppingQuantity('dos botes de tomate'),{name:'tomate',qty:2,unit:'botes'});
assert.equal(interpretShoppingRequest('Quiero comprar pan y guardar dos bricks de leche en la despensa').home[0].kind,'stock');
assert.equal(interpretShoppingRequest('Comprar pollo y luego guarda tres raciones de arroz en el congelador').home[0].location,'Congelador');
assert.ok(shoppingInputNeedsReview('No compres queso, ya tenemos'));
assert.equal(interpretHouseholdNote('Come fuera pero lleva tupper de casa')?.presence,'variable');
assert.equal(interpretHouseholdNote('Come fuera entre semana')?.presence,'fuera_dia');
assert.equal(interpretHouseholdNote('No come fuera')?.presence,'casa');
assert.equal(interpretHouseholdNote('Come en casa pero algunos días sale')?.presence,'variable');
assert.equal(interpretHouseholdNote('Nos gustan los domingos'),undefined);
assert.equal(weeklyBudgetToMonthly(75),325);assert.equal(weeklyBudgetToMonthly(Infinity),0);
assert.equal(normalizeSupermarket('costco'),'Costco');assert.equal(normalizeSupermarket('ldl'),'Lidl');
assert.ok(quickStockChoices('Leche','bricks').some(x=>x.qty===12&&x.unit==='bricks'));
console.log('PASS: conversational purchases separated from Casa, milk containers, no invented pack volume, optional routines and weekly budgets');
