import assert from 'node:assert/strict';
import {normalizeState,completePurchase,attachReceiptToPurchase,consumeRecipeIngredients} from '../components/homeos';
import {possibleExistingPurchase,replenishmentCandidates,comparePurchasePriority} from '../lib/inventory-advice';
import {observeStock} from '../lib/quick-inventory';
import {estimateConsumption,estimateInventoryConsumption} from '../lib/consumption-engine';
import {mergeHouseholdState} from '../lib/sync-merge';
const initial=normalizeState({profile:{onboardingDone:true},inventory:[{id:'old',name:'Leche',qty:1,unit:'L',category:'Lácteos',stock:'hay',location:'Despensa',purchasedAt:'2026-10-01'}]});
const pending={id:'new',name:'Leche',qty:1,unit:'L',category:'Lácteos',status:'carrito' as const,reason:'persona' as const,requestedBy:'Hugo'};
const next=completePurchase({...initial,shopping:[pending]},['new'],2,'Lidl','2026-10-08');
assert.equal(next.inventory.length,2);
assert.deepEqual(next.inventory.find(i=>i.id==='old'),initial.inventory[0]);
assert.equal(next.inventory[0].purchasedAt,'2026-10-08');
assert.equal(next.inventory[0].purchaseSessionId,next.purchaseSessions[0].id);
assert.equal(completePurchase(next,['new'],2,'Lidl','2026-10-08'),next);
assert.match(possibleExistingPurchase(next.inventory,pending,'2026-10-08')!.text,/7 días/);
assert.equal(possibleExistingPurchase([{...initial.inventory[0],stock:'falta',qty:0}],pending),null);
const frozen={...initial.inventory[0],id:'frozen',location:'Congelador' as const};
assert.match(possibleExistingPurchase([frozen],pending,'2026-10-08')!.text,/congelador/);
const receipt=[{name:'Leche',qty:1,raw:'Leche 2,00'}];
const linked=attachReceiptToPurchase(next,next.purchaseSessions[0].id,receipt,2.5);
assert.equal(linked.inventory.length,2);assert.equal(linked.spent,2.5);assert.equal(linked.purchaseSessions.length,1);
assert.equal(attachReceiptToPurchase(linked,linked.purchaseSessions[0].id,receipt,2.5).spent,2.5);
const extras=attachReceiptToPurchase(linked,linked.purchaseSessions[0].id,[...receipt,{name:'Huevos',qty:6,raw:'Huevos 3,00'}],5.5);
assert.equal(extras.inventory.length,3);assert.equal(extras.spent,5.5);assert.equal(extras.purchaseSessions.length,1);
assert.equal(attachReceiptToPurchase(extras,extras.purchaseSessions[0].id,[...receipt,{name:'Huevos',qty:6,raw:'Huevos 3,00'}],5.5).inventory.length,3);
const larger=attachReceiptToPurchase(linked,linked.purchaseSessions[0].id,[{...receipt[0],qty:2}],4);
assert.equal(larger.inventory.filter(i=>i.purchaseSessionId===linked.purchaseSessions[0].id).reduce((n,i)=>n+i.qty,0),1,'receipt packaging cannot be silently converted to litres');
const lows=next.inventory.map(i=>({...i,stock:'falta',qty:0}));
assert.equal(replenishmentCandidates(lows,[],()=>.03).length,1);
assert.equal(replenishmentCandidates(lows,[pending],()=>.03).length,0);
assert.equal(replenishmentCandidates([...lows,frozen],[],i=>i.id==='frozen'?.9:.03).length,0);
assert.equal(replenishmentCandidates(lows,[],()=>.03,[lows[0].id]).length,0);
const present=observeStock(initial.inventory[0],'queda','2026-10-08');
assert.equal(present.qty,1);assert.equal(present.lastConfirmedAt,undefined);
const habit=[{id:'milk',name:'Leche',qty:1,unit:'L',days:7}];
assert.equal(estimateInventoryConsumption(next.inventory.find(i=>i.id==='old')!,next.inventory,[],habit,[],'2026-10-08').estimatedQty,0);
assert.equal(estimateInventoryConsumption(next.inventory[0],next.inventory,[],habit,[],'2026-10-08').estimatedQty,1);
assert.equal(estimateInventoryConsumption(next.inventory[0],next.inventory,[],habit,[],'2026-10-15').estimatedQty,0);
assert.equal(estimateConsumption(initial.inventory[0],[],habit,[],'2026-10-08').estimatedQty,0);
assert.ok(estimateConsumption(present,[],habit,[],'2026-10-08').estimatedQty>0);
assert.equal(present.purchasedAt,'2026-10-01');
const used=consumeRecipeIngredients(next.inventory,[{name:'Leche',key:'leche',qty:'500 ml'}]);
assert.equal(used.inventory.find(i=>i.id==='old')!.qty,.5);
assert.equal(used.inventory.find(i=>i.id===next.inventory[0].id)!.qty,1);
assert.equal([...next.inventory].sort(comparePurchasePriority)[0].id,'old');
const other=completePurchase({...initial,shopping:[{...pending,id:'other'}]},['other'],3,'Mercadona','2026-10-08');
const shared=mergeHouseholdState(initial,next,other);
assert.equal(shared.inventory.length,3);assert.equal(shared.spent,5);
console.log('PASS: dated lots, oldest-first recipes, explicit receipt linking and idempotence, household sync, remaining stock and duplicate-free suggestions');
